# other aprouch for webscarping

### Laberies

In [1]:
# libraries
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from bs4 import BeautifulSoup
from urllib.parse import quote_plus
import time
import csv
from datetime import datetime
from dotenv import load_dotenv
import pandas as pd
import os

### agrements / vairbales

In [ ]:
# --- CONFIG ---
JOB_KEYWORD = "Data scientist"
COUNTRIES = ["spain", "european union"]
DATE_POSTED = "24h" 
EXPERIENCE_LEVELS = ["2","3","4","5"]
WORKPLACE_TYPES = ["2"]

# DATE_POSTED codes:            # EXPERIENCE_LEVELS codes:          # WORKPLACE_TYPES codes:    
# "any" = Any time              # [] = All levels                   # [] = All types       
# "24h" = Past 24 hours         # ["1"] = Internship                # ["1"] = On-site  
# "week" = Past week            # ["2"] = Entry level               # ["2"] = Remote   
# "month" = Past month          # ["3"] = Associate                 # ["3"] = Hybrid   
                                # ["4"] = Mid-Senior level          
                                # ["5"] = Director                  
                                # ["6"] = Executive

In [3]:
# --- SCROLL ---
MAX_SCROLL_ATTEMPTS = 200
SCROLL_PAUSE = 5
DETAIL_PAUSE = 2

In [4]:
# --- SETUP CHROME ---
options = Options()
options.add_argument("--start-maximized")
options.add_argument("--incognito")
driver = webdriver.Chrome(options=options)

### Functions

In [5]:
# --- HELPER FUNCTIONS ---
def build_linkedin_url(keyword, location, exp_levels, workplace_types, date_posted):
    exp_param = ",".join(exp_levels) if exp_levels else ""
    workplace_param = ",".join(workplace_types) if workplace_types else ""
    date_param = ""
    if date_posted == "24h": date_param = "r86400"
    elif date_posted == "week": date_param = "r604800"
    elif date_posted == "month": date_param = "r2592000"

    url = f"https://www.linkedin.com/jobs/search/?keywords={quote_plus(keyword)}&location={quote_plus(location)}"
    if exp_param: url += f"&f_E={exp_param}"
    if workplace_param: url += f"&f_WT={workplace_param}"
    if date_param: url += f"&f_TPR={date_param}"
    url += "&position=1&pageNum=0"
    return url

In [6]:
def scroll_page(driver):
    attempt = 0
    last_height = driver.execute_script("return document.body.scrollHeight")
    while attempt < MAX_SCROLL_ATTEMPTS:
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(SCROLL_PAUSE)
        try:
            show_more_btn = WebDriverWait(driver, 5).until(
                EC.element_to_be_clickable((By.CLASS_NAME, "infinite-scroller__show-more-button"))
            )
            show_more_btn.click()
            time.sleep(SCROLL_PAUSE)
        except:
            pass
        new_height = driver.execute_script("return document.body.scrollHeight")
        if new_height == last_height:
            break
        last_height = new_height
        attempt += 1

In [7]:
def fetch_job_details(job_url):
    job_desc = ""
    company_desc = ""
    if not job_url: 
        return job_desc, company_desc
    try:
        driver.get(job_url)
        time.sleep(DETAIL_PAUSE)
        WebDriverWait(driver, 5).until(
            EC.presence_of_element_located((By.CLASS_NAME, "description__text"))
        )
        job_soup = BeautifulSoup(driver.page_source, "html.parser")
        job_div = job_soup.find("div", class_="description__text")
        job_desc = job_div.get_text(separator="\n", strip=True) if job_div else ""
        company_div = job_soup.find("div", class_="show-more-less-html__markup")
        company_desc = company_div.get_text(separator="\n", strip=True) if company_div else ""
    except Exception as e:
        print(f"⚠️ Failed to fetch job detail: {e}")
    return job_desc, company_desc

In [8]:
# --- MAIN SCRAPING LOOP ---
all_jobs = []

for country in COUNTRIES:
    print(f"=== Scraping LinkedIn Jobs for {country} ===")
    url = build_linkedin_url(JOB_KEYWORD, country, EXPERIENCE_LEVELS, WORKPLACE_TYPES, DATE_POSTED)
    print(f"🔗 URL: {url}")
    driver.get(url)
    scroll_page(driver)

    html = driver.page_source
    soup = BeautifulSoup(html, "html.parser")
    job_cards = soup.find_all("div", class_="base-card") 
    
    for idx, card in enumerate(job_cards):
        a_tag = card.find("a", class_="base-card__full-link")
        job_url = a_tag["href"].strip() if a_tag else ""
        job_title = a_tag.find("span", class_="sr-only").text.strip() if a_tag and a_tag.find("span", class_="sr-only") else ""
        company_tag = card.find("h4", class_="base-search-card__subtitle")
        company_a = company_tag.find("a") if company_tag else None
        company_name = company_a.text.strip() if company_a else ""
        company_url = company_a["href"].strip() if company_a else ""
        location = card.find("span", class_="job-search-card__location")
        location = location.text.strip() if location else ""
        benefit = card.find("span", class_="job-posting-benefits__text")
        benefit = benefit.text.strip() if benefit else ""
        posted = card.find("time", class_="job-search-card__listdate")
        posted = posted.text.strip() if posted else ""

        print(f"🔍 ({idx + 1}/{len(job_cards)}) Fetching job: {job_title}")
        job_description, company_description = fetch_job_details(job_url)

        all_jobs.append({
            "country": country,
            "job_title": job_title,
            "company_name": company_name,
            "company_url": company_url,
            "location": location,
            "benefit": benefit,
            "posted": posted,
            "company_description": company_description,
            "job_url": job_url,
            "job_description": job_description
        })


driver.quit()

=== Scraping LinkedIn Jobs for spain ===
🔗 URL: https://www.linkedin.com/jobs/search/?keywords=Data+scientist&location=spain&f_E=2,3,4,5,6&f_WT=2&f_TPR=r86400&position=1&pageNum=0
🔍 (1/70) Fetching job: Junior Data Scientist
🔍 (2/70) Fetching job: Data Scientist (Forecasting)
🔍 (3/70) Fetching job: Senior Data Scientist
🔍 (4/70) Fetching job: Programa Talento Joven - Data Science
🔍 (5/70) Fetching job: AI Engineer – Generative AI & Data Science
🔍 (6/70) Fetching job: Junior Developer - AI, App, Web, Cloud, Data, Machine Learning
🔍 (7/70) Fetching job: Python Software Engineer (Azure)
🔍 (8/70) Fetching job: Data Analyst/Engineer/Scientist
🔍 (9/70) Fetching job: Software Engineer - Python (Advanced)
🔍 (10/70) Fetching job: Hardcore Engineer (All Levels)
🔍 (11/70) Fetching job: Python AWS Data Engineer
🔍 (12/70) Fetching job: FullStack Development
🔍 (13/70) Fetching job: Software engineer
🔍 (14/70) Fetching job: Desarrollador react
🔍 (15/70) Fetching job: Software Developer
🔍 (16/70) Fetching job: Software engineer
🔍 (17/70) Fetching job: Software Engineer - Ruby
🔍 (18/70) Fetching job: Desarrollador/a Power Platform
🔍 (19/70) Fetching job: Senior AI QA Engineer (GenAI)
🔍 (20/70) Fetching job: Desarrollador MERN
🔍 (21/70) Fetching job: Software Engineer (Scientific and Analytical) - Remote
🔍 (22/70) Fetching job: Spanish (Mexico) Data Annotator
🔍 (23/70) Fetching job: Senior Tech Lead Spark Databricks
🔍 (24/70) Fetching job: 💾Azure Databricks Data Engineer
🔍 (25/70) Fetching job: Golang Developer
🔍 (26/70) Fetching job: Ingeniero/a C++ & Java – Telemetría Racing
🔍 (27/70) Fetching job: Data Platform Reliability Engineer - Postgres
🔍 (28/70) Fetching job: Experto/a Magnolia
🔍 (29/70) Fetching job: Data Engineer (Adobe RTCDP & Snowflake)
🔍 (30/70) Fetching job: MuleSoft Developer
🔍 (31/70) Fetching job: Software Engineer (Office Suite) - Remote
🔍 (32/70) Fetching job: Junior Data Analyst
🔍 (33/70) Fetching job: Data Analyst Junior
🔍 (34/70) Fetching job: Data Analyst
🔍 (35/70) Fetching job: Java Technical Lead (AWS & Testing) (100% remote Spain)
🔍 (36/70) Fetching job: Programador Oracle SOA + OSB | 100% Remoto desde España
🔍 (37/70) Fetching job: Senior Kafka Developer
🔍 (38/70) Fetching job: Senior Product Analyst
🔍 (39/70) Fetching job: 🚀 Snowflake Data Engineer
🔍 (40/70) Fetching job: Tech Lead - Web Platform
🔍 (41/70) Fetching job: Analista de Reporting | Remoto
🔍 (42/70) Fetching job: Desarrollador/a Angular | 100% remoto
🔍 (43/70) Fetching job: Technical Lead Salesforce
🔍 (44/70) Fetching job: Data Engineer (Azure)
🔍 (45/70) Fetching job: Senior GCP Data Engineer
🔍 (46/70) Fetching job: Java Tech Lead
🔍 (47/70) Fetching job: Senior QA Automation
🔍 (48/70) Fetching job: Software Engineer (DevOps) - Database Reliability
🔍 (49/70) Fetching job: Software Engineer (DevOps) - Database Reliability
🔍 (50/70) Fetching job: Data Engineer
🔍 (51/70) Fetching job: QA Engineer – International Projects
🔍 (52/70) Fetching job: VUE DEVELOPER
🔍 (53/70) Fetching job: Node Engineer - Senior
🔍 (54/70) Fetching job: Senior/Staff Flutter Engineer
🔍 (55/70) Fetching job: Senior backend GO
🔍 (56/70) Fetching job: Programador/a SharePoint
🔍 (57/70) Fetching job: Vue.js Software Developer
🔍 (58/70) Fetching job: Senior Salesforce Developer
🔍 (59/70) Fetching job: Senior Automation QA Engineer
🔍 (60/70) Fetching job: Senior Product Analyst
🔍 (61/70) Fetching job: Electrical Engineer with Python - Freelance AI Trainer
🔍 (62/70) Fetching job: Electrical Engineer with Python - Freelance AI Trainer
🔍 (63/70) Fetching job: Graduate software engineer
🔍 (64/70) Fetching job: Senior AI Agent Engineer
🔍 (65/70) Fetching job: Evaluation Scenario Writer - AI Agent Testing Specialist
🔍 (66/70) Fetching job: Automotive Engineer with Python - Freelance AI Trainer
🔍 (67/70) Fetching job: Evaluation Scenario Writer - AI Agent Testing Specialist
🔍 (68/70) Fetching job: Evaluation Scenario Writer - AI Agent Testing Specialist
🔍 (69/70) Fetching job: Técnico/A De Proyectos
🔍 (70/70) Fetching job: Full-Stack Product Engineer (Remote Europe)
=== Scraping LinkedIn Jobs for european union ===
🔗 URL: https://www.linkedin.com/jobs/search/?keywords=Data+scientist&location=european+union&f_E=2,3,4,5,6&f_WT=2&f_TPR=r86400&position=1&pageNum=0
🔍 (1/70) Fetching job: Junior Data Scientist
🔍 (2/70) Fetching job: Machine Learning Engineer (Remote)
🔍 (3/70) Fetching job: Machine Learning Engineer
🔍 (4/70) Fetching job: Machine Learning Engineer (m/w/d)
🔍 (5/70) Fetching job: Data Scientist (Forecasting)
🔍 (6/70) Fetching job: MLOps Engineer (Poland, Serbia, Croatia, Portugal)
🔍 (7/70) Fetching job: Senior Data Scientist
🔍 (8/70) Fetching job: Junior Data Science
🔍 (9/70) Fetching job: Senior Machine Learning Engineer
🔍 (10/70) Fetching job: Programa Talento Joven - Data Science
🔍 (11/70) Fetching job: AI Engineer – Generative AI & Data Science
🔍 (12/70) Fetching job: Senior Machine Learning Engineer
🔍 (13/70) Fetching job: Senior Machine Learning Engineer
🔍 (14/70) Fetching job: Senior Data Scientist (m/f/d)
🔍 (15/70) Fetching job: Applied Machine Learning Engineer
🔍 (16/70) Fetching job: Applied Machine Learning Engineer
🔍 (17/70) Fetching job: Applied Machine Learning Engineer
🔍 (18/70) Fetching job: Senior Machine Learning Engineer
🔍 (19/70) Fetching job: (Senior) Data Scientist - Operations (m/f/n)
🔍 (20/70) Fetching job: Junior Developer - AI, App, Web, Cloud, Data, Machine Learning
🔍 (21/70) Fetching job: Remote Data Scientist (Senior)
🔍 (22/70) Fetching job: (Senior) Data Scientist - Personalisation (m/f/n)
🔍 (23/70) Fetching job: Applied Machine Learning Engineer
🔍 (24/70) Fetching job: Remote Sr. Data Scientist
🔍 (25/70) Fetching job: Lead Data Scientist - Remote
🔍 (26/70) Fetching job: Lead Data Scientist (Remote)
🔍 (27/70) Fetching job: Remote Data Science Consultant - Sr.
🔍 (28/70) Fetching job: MLOps Engineer
🔍 (29/70) Fetching job: Python Software Engineer (Azure)
🔍 (30/70) Fetching job: MLOps Engineer
🔍 (31/70) Fetching job: MLOps Engineer
🔍 (32/70) Fetching job: MLOps Field Engineer
🔍 (33/70) Fetching job: Research Internship / Work-Study
🔍 (34/70) Fetching job: MLOps Engineer
🔍 (35/70) Fetching job: Sr. Data Scientist (Remote)
🔍 (36/70) Fetching job: Sr. Data Scientist - Remote
🔍 (37/70) Fetching job: Junior Engineer (Ingegneria) – STEM Background
🔍 (38/70) Fetching job: Oncology Clinical Researcher
🔍 (39/70) Fetching job: Remote Principal Data Scientist
🔍 (40/70) Fetching job: Data Analyst/Engineer/Scientist
🔍 (41/70) Fetching job: Software Engineer (AI-Native Platform & Integrations) | Remote
🔍 (42/70) Fetching job: Hardcore Engineer (All Levels)
🔍 (43/70) Fetching job: Software Engineer - Python - Container Images
🔍 (44/70) Fetching job: Software Developer (all genders)
🔍 (45/70) Fetching job: Software Engineer - Python (Advanced)
🔍 (46/70) Fetching job: Python and Kubernetes Software Engineer - Data, Workflows, AI/ML & Analytics
🔍 (47/70) Fetching job: Software Engineer (AI-Native Platform & Integrations) | Remote
🔍 (48/70) Fetching job: Software Engineer - Python - Container Images
🔍 (49/70) Fetching job: Software Engineer - Python (Advanced)
🔍 (50/70) Fetching job: Python and Kubernetes Software Engineer - Data, Workflows, AI/ML & Analytics
🔍 (51/70) Fetching job: Software Engineer (AI-Native Platform & Integrations) | Remote
🔍 (52/70) Fetching job: Hardcore Engineer (All Levels)
🔍 (53/70) Fetching job: Hardcore Engineer (All Levels)
🔍 (54/70) Fetching job: Hardcore Engineer (All Levels)
🔍 (55/70) Fetching job: Hardcore Engineer (All Levels)
🔍 (56/70) Fetching job: Software Engineer - Python - Container Images
🔍 (57/70) Fetching job: Entry-Level Quality Assurance Engineer
🔍 (58/70) Fetching job: Hardcore Engineer (All Levels)
🔍 (59/70) Fetching job: Hardcore Engineer (All Levels)
🔍 (60/70) Fetching job: Hardcore Engineer (All Levels)
🔍 (61/70) Fetching job: AI Design Engineer
🔍 (62/70) Fetching job: Mechanical Engineer with Python - Freelance AI Trainer
🔍 (63/70) Fetching job: Automotive Engineering & Python Expert - Freelance AI Trainer
🔍 (64/70) Fetching job: Automotive Engineering & Python Expert - Freelance AI Trainer
🔍 (65/70) Fetching job: Mechanical Engineer with Python - Freelance AI Trainer
🔍 (66/70) Fetching job: AI Engineer
🔍 (67/70) Fetching job: Automotive Engineering & Python Expert - Freelance AI Trainer
🔍 (68/70) Fetching job: Automotive Engineering & Python Expert - Freelance AI Trainer
🔍 (69/70) Fetching job: Mechanical Engineer with Python - Freelance AI Trainer
🔍 (70/70) Fetching job: Mechanical Engineer with Python - Freelance AI Trainer

In [10]:
all_jobs

[{'country': 'spain',
  'job_title': 'Junior Data Scientist',
  'company_name': 'Joinrs',
  'company_url': 'https://it.linkedin.com/company/joinrs-international?trk=public_jobs_jserp-result_job-search-card-subtitle',
  'location': 'Spain',
  'benefit': 'Actively Hiring',
  'posted': '',
  'company_description': 'Nuestro objetivo es ayudar a todos los recién graduados del mundo a encontrar el trabajo que más se ajuste a sus ambiciones: ¡únete a nosotros para hacer realidad las aspiraciones de una comunidad de más de 1,500,000 usuarios!\nObservamos constantemente los recursos de los estudiantes y egresados que aspiran a incorporarse a nuestro equipo de\nTecnología\n: los candidatos para este puesto y nuestro equipo de RRHH se pondrán en contacto contigo sin comunicar puesto y tu CV será el adecuado a tu perfil.\nPara estas posiciones junior en el sector\nTech\n, ofrecemos un contrato con una\nremuneración anual de 24.000€ a 28.000 €\n, dependiendo de la experiencia. Podrás trabajar en modalidad completamente remota y, por ello, te proporcionaremos en cualquier momento un MacBook de última generación.\n¡Nos vamos a España!\nSi quieres sumarte a crecer en tu país, envía tu CV para este anuncio: si tu perfil está en alguno de nuestros futuros puestos, nos pondremos en contacto contigo ;)\n--\nDentro del equipo de Tecnología podrás abordar diversas tareas como:\nImplementación de algoritmos de Machine Learning\n: tendrá la oportunidad de implementar y probar algoritmos de aprendizaje automático, ayudando a desarrollar soluciones inteligentes a los desafíos comerciales. En particular, junto con nuestro equipo tecnológico, trabajarás en Joinrs AI: nuestro modelo de Inteligencia Artificial que ayuda a nuestra comunidad a encontrar trabajo;\nAnálisis y modelado de datos:\nparticipará en el análisis de datos, desarrollará modelos predictivos y ayudará a proporcionar información significativa para mejorar las decisiones comerciales.\nVisualización de datos:\naprenderá a crear visualizaciones de datos claras e informativas para comunicar de manera efectiva hallazgos complejos a diferentes partes interesadas. En particular, creará paneles interactivos para mostrar mejor los datos y KPI (visualización de datos) al equipo, los clientes, los inversores y todas las partes interesadas clave;\nOptimización de Procesos de Negocio:\nColaborarás en la identificación y optimización de procesos de negocio mediante la aplicación de soluciones basadas en datos.\nParticipación en Sesiones de Brainstorming Tecnológico:\nParticiparás en sesiones de Brainstorming para generar ideas innovadoras y contribuirás a la identificación de nuevas oportunidades en el campo de la Inteligencia Artificial.\nFormación Continua y Actualización en las Últimas Tendencias:\nTendrás acceso a programas de formación continua para mantenerte actualizado sobre las últimas tendencias y avances en el campo de la Ciencia de Datos y la Inteligencia Artificial.\n--\nLo que te ofrecemos\nTrabajar en el equipo de Joinrs significa\npoder elegir siempre las mejores condiciones psicofísicas para estar sereno y productivo\n. Esto se traduce en:\nTrabajo remoto y flexibilidad.\nTendrás la oportunidad de trabajar completamente a distancia todo el tiempo que desees, pero también apoyarte en una de nuestras oficinas.\nAmbiente de trabajo dinámico.\nNuestras oficinas siempre están abiertas. Te garantizamos espacios de trabajo compartidos, salas de reuniones, áreas de descanso y un bar con frutas frescas y aperitivos de todo tipo. También encontrarás una mesa de billar y una estación de juegos. Queremos un ambiente de trabajo informal que fomente momentos de compartir, siempre respetando las actividades individuales.\nTeam building y diversión.\nOrganizamos a menudo aperitivos, juegos y momentos de recreo: son parte integral de la vida en Joinrs, tanto fuera como dentro de la oficina.\nBienestar empresarial.\nTe garantizamos un bienestar empresarial privado a la altura de tus expectativas.\nPaquete tecnológico.\nUtilizarás software avanzado y tecnologías modernas, y se te proporcionará un MacBook de última generación.\nFormación.\nSiempre contarás con un tutor en tu trayectoria en Joinrs: tendrás un punto de referencia tanto para los aspectos técnicos como para los del equipo. Te aseguramos un crecimiento profesional constante que se traducirá en un aumento progresivo de tus responsabilidades. Podrás participar en eventos del sector y cursos de formación, además de recibir formación continua en las mejores plataformas de aprendizaje en línea.\nImpacto social.\nTu contribución apoyará a miles de recién graduados a encontrar el trabajo al que aspiran: tendrás la oportunidad de interactuar con nuestra comunidad y descubrir el impacto social y la revolución que estamos llevando más allá de las fronteras italianas.\n--\nQuiénes somos\nNuestra misión es apoyar a cada recién graduado a lograr sus aspiraciones, permitiéndole comenzar su nueva carrera con el optimismo de una perspectiva clara.\nSomos un equipo unido que cree firmemente en el trabajo en equipo:\njuntos trabajamos, discutimos y obtenemos resultados que nos estimulan a alcanzar objetivos cada vez más ambiciosos.\nNuestra comunidad cuenta con más de\n1,500,000 miembros en Italia, Reino Unido, España, Brasil, Francia, Portugal y Alemania\n, incluyendo\n700 empresas\ncomo\nPwC, Accenture, Gi Group, Danone, Siemens,\ny está creciendo de manera exponencial: ¡únete a nosotros!\n--\nContrato y Remuneración:\nPara todos los puestos de\nJunior Data Scientist\nofrecemos un\ncontrato con un salari anualo de €24,000 a €28.000\n.\nSe programará una revisión salarial cada seis meses,\ny tu remuneración crecerá rápidamente a medida que acumules experiencia y la traduzcas en un impacto cada vez mayor.\n--\nProceso de selección:\n1. Revisión del CV:\nel primer paso es una revisión del currículum (generalmente dentro de los 20 días posteriores a la solicitud).\n2. Entrevista telefónica:\nel segundo paso incluirá una entrevista telefónica con nuestro Gerente de Recursos Humanos de aproximadamente 15 minutos.\n3. Entrevista por video:\nel último paso será una entrevista por video con tanto el Gerente de Recursos Humanos como tu futuro supervisor. Prevemos al menos 45 minutos de entrevista.\n--\n¿Por qué unirte a nuestro equipo?\nImpacto social:\ntendrás la oportunidad de apoyar a nuestra comunidad para que logren sus aspiraciones. Y las tuyas.\nStartup exitosa:\nJoinrs fue seleccionada entre las 10 mejores startups del mundo en la Web Summit de Lisboa.\nCrecimiento personal exponencial:\ntendrás la oportunidad de crecer de manera exponencial, tanto en habilidades técnicas como en habilidades blandas, gracias a un programa de formación basado en la capacitación en el trabajo y el apoyo en línea.',
  'job_url': 'https://es.linkedin.com/jobs/view/junior-data-scientist-at-joinrs-4379786993?position=1&pageNum=0&refId=8JnET%2BOPbdRq3GBjP1BAYg%3D%3D&trackingId=94Jr7xt2FLVQBhFnqlyEUA%3D%3D',
  'job_description': 'Nuestro objetivo es ayudar a todos los recién graduados del mundo a encontrar el trabajo que más se ajuste a sus ambiciones: ¡únete a nosotros para hacer realidad las aspiraciones de una comunidad de más de 1,500,000 usuarios!\nObservamos constantemente los recursos de los estudiantes y egresados que aspiran a incorporarse a nuestro equipo de\nTecnología\n: los candidatos para este puesto y nuestro equipo de RRHH se pondrán en contacto contigo sin comunicar puesto y tu CV será el adecuado a tu perfil.\nPara estas posiciones junior en el sector\nTech\n, ofrecemos un contrato con una\nremuneración anual de 24.000€ a 28.000 €\n, dependiendo de la experiencia. Podrás trabajar en modalidad completamente remota y, por ello, te proporcionaremos en cualquier momento un MacBook de última generación.\n¡Nos vamos a España!\nSi quieres sumarte a crecer en tu país, envía tu CV para este anuncio: si tu perfil está en alguno de nuestros futuros puestos, nos pondremos en contacto contigo ;)\n--\nDentro del equipo de Tecnología podrás abordar diversas tareas como:\nImplementación de algoritmos de Machine Learning\n: tendrá la oportunidad de implementar y probar algoritmos de aprendizaje automático, ayudando a desarrollar soluciones inteligentes a los desafíos comerciales. En particular, junto con nuestro equipo tecnológico, trabajarás en Joinrs AI: nuestro modelo de Inteligencia Artificial que ayuda a nuestra comunidad a encontrar trabajo;\nAnálisis y modelado de datos:\nparticipará en el análisis de datos, desarrollará modelos predictivos y ayudará a proporcionar información significativa para mejorar las decisiones comerciales.\nVisualización de datos:\naprenderá a crear visualizaciones de datos claras e informativas para comunicar de manera efectiva hallazgos complejos a diferentes partes interesadas. En particular, creará paneles interactivos para mostrar mejor los datos y KPI (visualización de datos) al equipo, los clientes, los inversores y todas las partes interesadas clave;\nOptimización de Procesos de Negocio:\nColaborarás en la identificación y optimización de procesos de negocio mediante la aplicación de soluciones basadas en datos.\nParticipación en Sesiones de Brainstorming Tecnológico:\nParticiparás en sesiones de Brainstorming para generar ideas innovadoras y contribuirás a la identificación de nuevas oportunidades en el campo de la Inteligencia Artificial.\nFormación Continua y Actualización en las Últimas Tendencias:\nTendrás acceso a programas de formación continua para mantenerte actualizado sobre las últimas tendencias y avances en el campo de la Ciencia de Datos y la Inteligencia Artificial.\n--\nLo que te ofrecemos\nTrabajar en el equipo de Joinrs significa\npoder elegir siempre las mejores condiciones psicofísicas para estar sereno y productivo\n. Esto se traduce en:\nTrabajo remoto y flexibilidad.\nTendrás la oportunidad de trabajar completamente a distancia todo el tiempo que desees, pero también apoyarte en una de nuestras oficinas.\nAmbiente de trabajo dinámico.\nNuestras oficinas siempre están abiertas. Te garantizamos espacios de trabajo compartidos, salas de reuniones, áreas de descanso y un bar con frutas frescas y aperitivos de todo tipo. También encontrarás una mesa de billar y una estación de juegos. Queremos un ambiente de trabajo informal que fomente momentos de compartir, siempre respetando las actividades individuales.\nTeam building y diversión.\nOrganizamos a menudo aperitivos, juegos y momentos de recreo: son parte integral de la vida en Joinrs, tanto fuera como dentro de la oficina.\nBienestar empresarial.\nTe garantizamos un bienestar empresarial privado a la altura de tus expectativas.\nPaquete tecnológico.\nUtilizarás software avanzado y tecnologías modernas, y se te proporcionará un MacBook de última generación.\nFormación.\nSiempre contarás con un tutor en tu trayectoria en Joinrs: tendrás un punto de referencia tanto para los aspectos técnicos como para los del equipo. Te aseguramos un crecimiento profesional constante que se traducirá en un aumento progresivo de tus responsabilidades. Podrás participar en eventos del sector y cursos de formación, además de recibir formación continua en las mejores plataformas de aprendizaje en línea.\nImpacto social.\nTu contribución apoyará a miles de recién graduados a encontrar el trabajo al que aspiran: tendrás la oportunidad de interactuar con nuestra comunidad y descubrir el impacto social y la revolución que estamos llevando más allá de las fronteras italianas.\n--\nQuiénes somos\nNuestra misión es apoyar a cada recién graduado a lograr sus aspiraciones, permitiéndole comenzar su nueva carrera con el optimismo de una perspectiva clara.\nSomos un equipo unido que cree firmemente en el trabajo en equipo:\njuntos trabajamos, discutimos y obtenemos resultados que nos estimulan a alcanzar objetivos cada vez más ambiciosos.\nNuestra comunidad cuenta con más de\n1,500,000 miembros en Italia, Reino Unido, España, Brasil, Francia, Portugal y Alemania\n, incluyendo\n700 empresas\ncomo\nPwC, Accenture, Gi Group, Danone, Siemens,\ny está creciendo de manera exponencial: ¡únete a nosotros!\n--\nContrato y Remuneración:\nPara todos los puestos de\nJunior Data Scientist\nofrecemos un\ncontrato con un salari anualo de €24,000 a €28.000\n.\nSe programará una revisión salarial cada seis meses,\ny tu remuneración crecerá rápidamente a medida que acumules experiencia y la traduzcas en un impacto cada vez mayor.\n--\nProceso de selección:\n1. Revisión del CV:\nel primer paso es una revisión del currículum (generalmente dentro de los 20 días posteriores a la solicitud).\n2. Entrevista telefónica:\nel segundo paso incluirá una entrevista telefónica con nuestro Gerente de Recursos Humanos de aproximadamente 15 minutos.\n3. Entrevista por video:\nel último paso será una entrevista por video con tanto el Gerente de Recursos Humanos como tu futuro supervisor. Prevemos al menos 45 minutos de entrevista.\n--\n¿Por qué unirte a nuestro equipo?\nImpacto social:\ntendrás la oportunidad de apoyar a nuestra comunidad para que logren sus aspiraciones. Y las tuyas.\nStartup exitosa:\nJoinrs fue seleccionada entre las 10 mejores startups del mundo en la Web Summit de Lisboa.\nCrecimiento personal exponencial:\ntendrás la oportunidad de crecer de manera exponencial, tanto en habilidades técnicas como en habilidades blandas, gracias a un programa de formación basado en la capacitación en el trabajo y el apoyo en línea.\nShow more\nShow less'},
 {'country': 'spain',
  'job_title': 'Data Scientist (Forecasting)',
  'company_name': 'WeHunt España',
  'company_url': 'https://es.linkedin.com/company/wehunt-espana?trk=public_jobs_jserp-result_job-search-card-subtitle',
  'location': 'Spain',
  'benefit': 'Be an early applicant',
  'posted': '',
  'company_description': 'Rol de\nSenior Data Scientist (Forecasting)\n100% Remoto\nDescripción del puesto de trabajo\nFormarás parte de\nproyectos punteros de su ecosistema\n, participando en el desarrollo e industrialización de modelos de predicción aplicados a casos reales de negocio.\nTendrás un\nrol clave como perfil senior\n, aportando criterio técnico, impulsando buenas prácticas y contribuyendo activamente al crecimiento del equipo.\nResponsabilidades\nDesarrollar e industrializar modelos de\nforecasting\npara casos reales de negocio.\nLiderar técnicamente proyectos y promover\nbuenas prácticas de Data Science y MLOps\n.\nImplementar y mantener pipelines y modelos en\nproducción en AWS\n.\nMonitorizar el rendimiento de los modelos y gestionar\nretraining y drift\n.\nColaborar con equipos de negocio y mentorar a perfiles del equipo.\nPerfil buscado (H/M/D)\nDominio avanzado de\nPython\n.\nExperiencia con\nPySpark\npara procesamiento de datos a gran escala.\nExperiencia trabajando en\nentornos AWS\n(S3, EC2, SageMaker, Lambda, EMR o similares).\nExperiencia desplegando y manteniendo\nmodelos en producción\n.\nConocimiento sólido de\nbuenas prácticas de MLOps\nExperiencia con modelos de\nforecasting\n, como:\nQué ofrecemos\nProyecto\nestable y de largo recorrido\n100% remoto\nIncorporación inmediata\nProyecto técnicamente muy interesante\nSalario competitivo (hasta 50.000 €)\nSiguientes pasos\nSi estás interesado en esta oferta, haz click en "aplicar ahora" para enviar una copia actualizada de tu CV o visita nuestro sitio web para más información.',
  'job_url': 'https://es.linkedin.com/jobs/view/data-scientist-forecasting-at-wehunt-espa%C3%B1a-4378804878?position=2&pageNum=0&refId=8JnET%2BOPbdRq3GBjP1BAYg%3D%3D&trackingId=oMwURqrV8DLC6k3DTww0ew%3D%3D',
  'job_description': 'Rol de\nSenior Data Scientist (Forecasting)\n100% Remoto\nDescripción del puesto de trabajo\nFormarás parte de\nproyectos punteros de su ecosistema\n, participando en el desarrollo e industrialización de modelos de predicción aplicados a casos reales de negocio.\nTendrás un\nrol clave como perfil senior\n, aportando criterio técnico, impulsando buenas prácticas y contribuyendo activamente al crecimiento del equipo.\nResponsabilidades\nDesarrollar e industrializar modelos de\nforecasting\npara casos reales de negocio.\nLiderar técnicamente proyectos y promover\nbuenas prácticas de Data Science y MLOps\n.\nImplementar y mantener pipelines y modelos en\nproducción en AWS\n.\nMonitorizar el rendimiento de los modelos y gestionar\nretraining y drift\n.\nColaborar con equipos de negocio y mentorar a perfiles del equipo.\nPerfil buscado (H/M/D)\nDominio avanzado de\nPython\n.\nExperiencia con\nPySpark\npara procesamiento de datos a gran escala.\nExperiencia trabajando en\nentornos AWS\n(S3, EC2, SageMaker, Lambda, EMR o similares).\nExperiencia desplegando y manteniendo\nmodelos en producción\n.\nConocimiento sólido de\nbuenas prácticas de MLOps\nExperiencia con modelos de\nforecasting\n, como:\nQué ofrecemos\nProyecto\nestable y de largo recorrido\n100% remoto\nIncorporación inmediata\nProyecto técnicamente muy interesante\nSalario competitivo (hasta 50.000 €)\nSiguientes pasos\nSi estás interesado en esta oferta, haz click en "aplicar ahora" para enviar una copia actualizada de tu CV o visita nuestro sitio web para más información.\nShow more\nShow less'},
 {'country': 'spain',
  'job_title': 'Senior Data Scientist',
  'company_name': 'AI Superior',
  'company_url': 'https://de.linkedin.com/company/ai-superior?trk=public_jobs_jserp-result_job-search-card-subtitle',
  'location': 'Spain',
  'benefit': 'Be an early applicant',
  'posted': '',

In [11]:
df = pd.DataFrame(all_jobs)
df.head()

,country,job_title,company_name,company_url,location,benefit,posted,company_description,job_url,job_description
0,spain,Junior Data Scientist,Joinrs,https://it.linkedin.com/company/joinrs-interna...,Spain,Actively Hiring,,Nuestro objetivo es ayudar a todos los recién ...,https://es.linkedin.com/jobs/view/junior-data-...,Nuestro objetivo es ayudar a todos los recién ...
1,spain,Data Scientist (Forecasting),WeHunt España,https://es.linkedin.com/company/wehunt-espana?...,Spain,Be an early applicant,,Rol de\nSenior Data Scientist (Forecasting)\n1...,https://es.linkedin.com/jobs/view/data-scienti...,Rol de\nSenior Data Scientist (Forecasting)\n1...
2,spain,Senior Data Scientist,AI Superior,https://de.linkedin.com/company/ai-superior?tr...,Spain,Be an early applicant,,About the role\nAI Superior is an AI agency fo...,https://es.linkedin.com/jobs/view/senior-data-...,About the role\nAI Superior is an AI agency fo...
3,spain,Programa Talento Joven - Data Science,Evolve,https://es.linkedin.com/school/evolve-es/?trk=...,Spain,Be an early applicant,,Descripción de la oferta\nEn nuestro Programa ...,https://es.linkedin.com/jobs/view/programa-tal...,Descripción de la oferta\nEn nuestro Programa ...
4,spain,AI Engineer – Generative AI & Data Science,ISPROX,https://es.linkedin.com/company/isproxwork?trk...,Spain,Actively Hiring,,"Desde ISPROX, colaboramos con empresa de consu...",https://es.linkedin.com/jobs/view/ai-engineer-...,"Desde ISPROX, colaboramos con empresa de consu..."

In [12]:
def remove_job_description_duplicates(df):
    df = df.copy()
    
    # Find duplicates (only the repeated ones, not the first occurrence)
    duplicate_count = df.duplicated(subset=["job_description"]).sum()
    print(f"Found {duplicate_count} duplicate rows.")
    
    # Keep first occurrence, remove the rest
    df_clean = df.drop_duplicates(subset=["job_description"], keep="first")
    
    print(f"New dataframe shape: {df_clean.shape}")
    
    return df_clean

In [13]:
remove_job_description_duplicates(df)

Found 46 duplicate rows.
New dataframe shape: (94, 10)

,country,job_title,company_name,company_url,location,benefit,posted,company_description,job_url,job_description
0,spain,Junior Data Scientist,Joinrs,https://it.linkedin.com/company/joinrs-interna...,Spain,Actively Hiring,,Nuestro objetivo es ayudar a todos los recién ...,https://es.linkedin.com/jobs/view/junior-data-...,Nuestro objetivo es ayudar a todos los recién ...
1,spain,Data Scientist (Forecasting),WeHunt España,https://es.linkedin.com/company/wehunt-espana?...,Spain,Be an early applicant,,Rol de\nSenior Data Scientist (Forecasting)\n1...,https://es.linkedin.com/jobs/view/data-scienti...,Rol de\nSenior Data Scientist (Forecasting)\n1...
2,spain,Senior Data Scientist,AI Superior,https://de.linkedin.com/company/ai-superior?tr...,Spain,Be an early applicant,,About the role\nAI Superior is an AI agency fo...,https://es.linkedin.com/jobs/view/senior-data-...,About the role\nAI Superior is an AI agency fo...
3,spain,Programa Talento Joven - Data Science,Evolve,https://es.linkedin.com/school/evolve-es/?trk=...,Spain,Be an early applicant,,Descripción de la oferta\nEn nuestro Programa ...,https://es.linkedin.com/jobs/view/programa-tal...,Descripción de la oferta\nEn nuestro Programa ...
4,spain,AI Engineer – Generative AI & Data Science,ISPROX,https://es.linkedin.com/company/isproxwork?trk...,Spain,Actively Hiring,,"Desde ISPROX, colaboramos con empresa de consu...",https://es.linkedin.com/jobs/view/ai-engineer-...,"Desde ISPROX, colaboramos con empresa de consu..."
...,...,...,...,...,...,...,...,...,...,...
130,european union,AI Design Engineer,MindCanvas,https://www.linkedin.com/company/mindcanvas-ap...,Germany,,,"THIS IS A PRODUCT/UX DESIGNER POSITION, NOT FO...",https://de.linkedin.com/jobs/view/ai-design-en...,"THIS IS A PRODUCT/UX DESIGNER POSITION, NOT FO..."
131,european union,Mechanical Engineer with Python - Freelance AI...,Mindrift,https://www.linkedin.com/company/mindrift-ai?t...,Italy,Be an early applicant,,Please submit your CV in English and indicate ...,https://it.linkedin.com/jobs/view/mechanical-e...,Please submit your CV in English and indicate ...
134,european union,Mechanical Engineer with Python - Freelance AI...,Mindrift,https://www.linkedin.com/company/mindrift-ai?t...,Ireland,Be an early applicant,,Please submit your CV in English and indicate ...,https://ie.linkedin.com/jobs/view/mechanical-e...,Please submit your CV in English and indicate ...
135,european union,AI Engineer,Talent Insights,https://es.linkedin.com/company/talentinsights...,Spain,Actively Hiring,,Talent Insights is the Business Insights divis...,https://es.linkedin.com/jobs/view/ai-engineer-...,Talent Insights is the Business Insights divis...
136,european union,Automotive Engineering & Python Expert - Freel...,Mindrift,https://www.linkedin.com/company/mindrift-ai?t...,"Paris, Île-de-France, France",Be an early applicant,,Please submit your CV in English and indicate ...,https://fr.linkedin.com/jobs/view/automotive-e...,Please submit your CV in English and indicate ...

In [15]:
df.to_csv("jobs_bryan_02_03.csv", index=False)