# other aprouch for webscarping

### Laberies

In [2]:
# libraries
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from bs4 import BeautifulSoup
from urllib.parse import quote_plus
import time
import csv
from datetime import datetime
from dotenv import load_dotenv
import os

### agrements / vairbales

In [16]:
# --- CONFIG ---
JOB_KEYWORD = "Data scientist"
COUNTRIES = ["spain"]
DATE_POSTED = "month"
EXPERIENCE_LEVELS = ["2","3"]
WORKPLACE_TYPES = ["1","2","3"]

# DATE_POSTED codes:            # EXPERIENCE_LEVELS codes:          # WORKPLACE_TYPES codes:    
# "any" = Any time              # [] = All levels                   # [] = All types       
# "24h" = Past 24 hours         # ["1"] = Internship                # ["1"] = On-site  
# "week" = Past week            # ["2"] = Entry level               # ["2"] = Remote   
# "month" = Past month          # ["3"] = Associate                 # ["3"] = Hybrid   
                                # ["4"] = Mid-Senior level          
                                # ["5"] = Director                  
                                # ["6"] = Executive

In [17]:
# --- SCROLL ---
MAX_SCROLL_ATTEMPTS = 200
SCROLL_PAUSE = 5
DETAIL_PAUSE = 2

In [18]:
# --- SETUP CHROME ---
options = Options()
options.add_argument("--start-maximized")
options.add_argument("--incognito")
driver = webdriver.Chrome(options=options)

### Functions

In [19]:
# --- HELPER FUNCTIONS ---
def build_linkedin_url(keyword, location, exp_levels, workplace_types, date_posted):
    exp_param = ",".join(exp_levels) if exp_levels else ""
    workplace_param = ",".join(workplace_types) if workplace_types else ""
    date_param = ""
    if date_posted == "24h": date_param = "r86400"
    elif date_posted == "week": date_param = "r604800"
    elif date_posted == "month": date_param = "r2592000"

    url = f"https://www.linkedin.com/jobs/search/?keywords={quote_plus(keyword)}&location={quote_plus(location)}"
    if exp_param: url += f"&f_E={exp_param}"
    if workplace_param: url += f"&f_WT={workplace_param}"
    if date_param: url += f"&f_TPR={date_param}"
    url += "&position=1&pageNum=0"
    return url

In [20]:
def scroll_page(driver):
    attempt = 0
    last_height = driver.execute_script("return document.body.scrollHeight")
    while attempt < MAX_SCROLL_ATTEMPTS:
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(SCROLL_PAUSE)
        try:
            show_more_btn = WebDriverWait(driver, 5).until(
                EC.element_to_be_clickable((By.CLASS_NAME, "infinite-scroller__show-more-button"))
            )
            show_more_btn.click()
            time.sleep(SCROLL_PAUSE)
        except:
            pass
        new_height = driver.execute_script("return document.body.scrollHeight")
        if new_height == last_height:
            break
        last_height = new_height
        attempt += 1

In [21]:
def fetch_job_details(job_url):
    job_desc = ""
    company_desc = ""
    if not job_url: 
        return job_desc, company_desc
    try:
        driver.get(job_url)
        time.sleep(DETAIL_PAUSE)
        WebDriverWait(driver, 5).until(
            EC.presence_of_element_located((By.CLASS_NAME, "description__text"))
        )
        job_soup = BeautifulSoup(driver.page_source, "html.parser")
        job_div = job_soup.find("div", class_="description__text")
        job_desc = job_div.get_text(separator="\n", strip=True) if job_div else ""
        company_div = job_soup.find("div", class_="show-more-less-html__markup")
        company_desc = company_div.get_text(separator="\n", strip=True) if company_div else ""
    except Exception as e:
        print(f"⚠️ Failed to fetch job detail: {e}")
    return job_desc, company_desc

In [22]:
# --- MAIN SCRAPING LOOP ---
all_jobs = []

for country in COUNTRIES:
    print(f"=== Scraping LinkedIn Jobs for {country} ===")
    url = build_linkedin_url(JOB_KEYWORD, country, EXPERIENCE_LEVELS, WORKPLACE_TYPES, DATE_POSTED)
    print(f"🔗 URL: {url}")
    driver.get(url)
    scroll_page(driver)

    html = driver.page_source
    soup = BeautifulSoup(html, "html.parser")
    job_cards = soup.find_all("div", class_="base-card") 
    
    for idx, card in enumerate(job_cards):
        a_tag = card.find("a", class_="base-card__full-link")
        job_url = a_tag["href"].strip() if a_tag else ""
        job_title = a_tag.find("span", class_="sr-only").text.strip() if a_tag and a_tag.find("span", class_="sr-only") else ""
        company_tag = card.find("h4", class_="base-search-card__subtitle")
        company_a = company_tag.find("a") if company_tag else None
        company_name = company_a.text.strip() if company_a else ""
        company_url = company_a["href"].strip() if company_a else ""
        location = card.find("span", class_="job-search-card__location")
        location = location.text.strip() if location else ""
        benefit = card.find("span", class_="job-posting-benefits__text")
        benefit = benefit.text.strip() if benefit else ""
        posted = card.find("time", class_="job-search-card__listdate")
        posted = posted.text.strip() if posted else ""

        print(f"🔍 ({idx + 1}/{len(job_cards)}) Fetching job: {job_title}")
        job_description, company_description = fetch_job_details(job_url)

        all_jobs.append({
            "country": country,
            "job_title": job_title,
            "company_name": company_name,
            "company_url": company_url,
            "location": location,
            "benefit": benefit,
            "posted": posted,
            "company_description": company_description,
            "job_url": job_url,
            "job_description": job_description
        })


driver.quit()

=== Scraping LinkedIn Jobs for spain ===
🔗 URL: https://www.linkedin.com/jobs/search/?keywords=Data+scientist&location=spain&f_E=2,3&f_WT=1,2,3&f_TPR=r2592000&position=1&pageNum=0
🔍 (1/70) Fetching job: 🚀📊 Científico/a de Datos (Data Scientist) (Científic de Dades)
🔍 (2/70) Fetching job: Data Scientist
🔍 (3/70) Fetching job: Data Scientist
🔍 (4/70) Fetching job: Data Scientist - 100% Teletrabajo
🔍 (5/70) Fetching job: MACHINE LEARNING ENGINEER / DATA ENGINEER
🔍 (6/70) Fetching job: 🐍📊 Ingeniero/a Desarrollo Back (Python, Pandas, PySpark)
🔍 (7/70) Fetching job: Data Scientist Innovación de Riesgos
🔍 (8/70) Fetching job: Data Scientist Junior
🔍 (9/70) Fetching job: Junior Machine Learning Engineer
🔍 (10/70) Fetching job: Data Scientist
🔍 (11/70) Fetching job: 📍 Data Scientist – ByRatings (Remote-Friendly | Flexible Hours)
🔍 (12/70) Fetching job: Data Engineer / Data Scientist
🔍 (13/70) Fetching job: Data Scientist – Machine Learning
🔍 (14/70) Fetching job: ML- GenAI Engineer
🔍 (15/70) Fetching job: Data Scientist - Advanced Analytics Madrid
🔍 (16/70) Fetching job: Junior Data Scientist
🔍 (17/70) Fetching job: Data Scientist
🔍 (18/70) Fetching job: 🚀Data Scientist - Data & Analytics 🚀
🔍 (19/70) Fetching job: Machine Learning Engineer
🔍 (20/70) Fetching job: Data Scientist – Evaluación de Modelos de IA
🔍 (21/70) Fetching job: Junior Data Scientist - Machine Learning
🔍 (22/70) Fetching job: Data Science - Machine Learning
🔍 (23/70) Fetching job: Data Scientist
🔍 (24/70) Fetching job: Data Scientist
🔍 (25/70) Fetching job: Desarrollador/a AI
🔍 (26/70) Fetching job: 🤖 ML Engineer ☁️🔬
🔍 (27/70) Fetching job: Machine Learning Engineer
🔍 (28/70) Fetching job: Data Scientist, Advanced and Product Analytics
🔍 (29/70) Fetching job: Data Scientist
🔍 (30/70) Fetching job: AI Specialist – Clinical NLP
🔍 (31/70) Fetching job: Applied Machine Learning Engineer (Junior / Mid-Level)
🔍 (32/70) Fetching job: Clinical Data Scientist
🔍 (33/70) Fetching job: IA Engineer
🔍 (34/70) Fetching job: Data Scientist
🔍 (35/70) Fetching job: Machine Learning Engineer | $77/hr Remote
🔍 (36/70) Fetching job: Data Scientist
🔍 (37/70) Fetching job: Machine Learning Engineer
🔍 (38/70) Fetching job: Data Scientist - Prompt
🔍 (39/70) Fetching job: Data Science
🔍 (40/70) Fetching job: Machine Learning Engineer
🔍 (41/70) Fetching job: Data Scientist
🔍 (42/70) Fetching job: Machine Learning Engineer (Re1-2) - Ai Factory (Earth Sciences Department)
🔍 (43/70) Fetching job: AI Engineer
🔍 (44/70) Fetching job: Data Scientist
🔍 (45/70) Fetching job: Data Scientist
🔍 (46/70) Fetching job: Data Scientist / IA Engineer
🔍 (47/70) Fetching job: Machine Learning Operations Engineer - Mlops (Re 1-2) – Ai Factory (Earth Sciences Department)
🔍 (48/70) Fetching job: Data Scientist-Kaggle Grandmaster | $77/hr Remote
🔍 (49/70) Fetching job: Data scientist
🔍 (50/70) Fetching job: Senior AI/ML  Engineer & Data Scientist
🔍 (51/70) Fetching job: Data scientist
🔍 (52/70) Fetching job: Data Scientist
🔍 (53/70) Fetching job: Data Scientist (Privacy)
🔍 (54/70) Fetching job: 🚀 Data Scientist / Ingeniero IA. IA Generativa 🧠.
🔍 (55/70) Fetching job: Programa Talento Joven - Data Science
🔍 (56/70) Fetching job: Senior Data Scientist - Remoto (45-50K)
🔍 (57/70) Fetching job: Data Scientist
🔍 (58/70) Fetching job: Sr. Data Scientist – Forecasting / 100% Remoto
🔍 (59/70) Fetching job: Senior Data Scientist
🔍 (60/70) Fetching job: GenAI Engineer
🔍 (61/70) Fetching job: 🚀📊 Científico/a de Datos (Data Scientist) (Científic de Dades)
🔍 (62/70) Fetching job: Data Scientist – Evaluación de Modelos de IA
🔍 (63/70) Fetching job: Data Scientist
🔍 (64/70) Fetching job: Tintadores De Cantos Y Suelas, A Mano
🔍 (65/70) Fetching job: HR Assistant
🔍 (66/70) Fetching job: Únete A Un Equipo Dinámico: Envía Tu Cv
🔍 (67/70) Fetching job: JOIN US COMUNIDAD VALENCIANA
🔍 (68/70) Fetching job: Entrenador
🔍 (69/70) Fetching job: Mozos De Carga Y Descarga, Almacén Y/O Mercado De Abastos
🔍 (70/70) Fetching job: 🚀Data Scientist - Data & Analytics 🚀

In [23]:
all_jobs

[{'country': 'spain',
  'job_title': '🚀📊 Científico/a de Datos (Data Scientist) (Científic de Dades)',
  'company_name': 'Quental',
  'company_url': 'https://es.linkedin.com/company/quental?trk=public_jobs_jserp-result_job-search-card-subtitle',
  'location': 'Barcelona, Catalonia, Spain',
  'benefit': '',
  'posted': '2 weeks ago',
  'company_description': '¿Te gustaría participar en un gran proyecto de modernización tecnológica que impacta directamente en la mejora de servicios públicos? 🌍\nBuscamos un/a\nCientífico/a de Datos\nque quiera formar parte de una iniciativa de actualización tecnológica de infraestructuras de aplicaciones, dentro de un entorno de IA, Big Data y mejora tecnológica avanzada.\nEl puesto es\nremoto 100%\n, aunque se valorará disponibilidad para asistir a reuniones muy esporádicas en Barcelona 🏙️.\n🎯 Serás una pieza clave en la definición, desarrollo y optimización de modelos analíticos y de inteligencia artificial, transformando datos en conocimiento estratégico que impulse la toma de decisiones y la mejora de servicios públicos.\n⚙️✨\n¿Qué harás en tu día a día?\n🧠 Definir objetivos analíticos y casos de uso de Inteligencia Artificial junto a negocio y equipos técnicos.\n📊 Realizar análisis exploratorio de datos para identificar patrones, tendencias y oportunidades de mejora.\n🤖 Diseñar, desarrollar, entrenar y optimizar modelos de Machine Learning y técnicas de analítica avanzada.\n📈 Evaluar rendimiento, validación y robustez de modelos mediante métricas y técnicas estadísticas.\n🧩 Seleccionar variables, preparar datasets y aplicar técnicas de feature engineering.\n🔬 Experimentar con algoritmos y metodologías para mejorar precisión y eficiencia de modelos.\n📉 Analizar resultados y generar insights accionables para negocio y stakeholders.\n🔗 Colaborar con equipos de Data Engineering para la integración y explotación de modelos en producción.\n☁️ Participar en entornos Big Data y ecosistemas cloud orientados a IA y analítica avanzada.\n📄 Documentar modelos, procesos analíticos y buenas prácticas metodológicas.\n🤝 Trabajar con equipos multidisciplinares (Arquitectura, Desarrollo, Negocio y Analítica).\n🧠\n¿Qué puedes aportarnos?\n📚 Titulación\nGrado en Estadística, Matemáticas, Física, Ingeniería Informática/Datos o similar\nMáster en Data Science, IA o equivalente.\n💼\nExperiencia\n⏳ Entre 2 y 8 años de experiencia en Ciencia de Datos, Analítica Avanzada o posiciones similares.\nExperiencia en desarrollo y evaluación de modelos de IA o Machine Learning en entornos reales.\n🛠️\nConocimientos técnicos\n🐍 Programación en Python aplicada a análisis de datos y modelos de IA.\n📊 Dominio de librerías de análisis y modelado (Pandas, NumPy, Scikit-learn, TensorFlow, PyTorch o similares).\n📈 Conocimientos sólidos en estadística, modelado predictivo y técnicas de Machine Learning.\n🧹 Experiencia en análisis exploratorio de datos y preparación de datasets.\n🗄️ Conocimientos de SQL y explotación de grandes volúmenes de datos.\n☁️ Conocimiento de ecosistemas Big Data y arquitecturas modernas de datos.\n📊 Experiencia en evaluación, validación y optimización de modelos analíticos.\n⭐\nMuy valorable\n🗣️ Nivel de comprensión y redacción en Catalán.\n⚡ Experiencia en procesamiento distribuido (PySpark o frameworks similares).\n🏛️ Experiencia en proyectos del sector público o grandes infraestructuras tecnológicas.\n☁️ Experiencia en entornos cloud aplicados a analítica avanzada e IA.\n📊 Experiencia en visualización de datos y comunicación de resultados analíticos.\n🤝 Experiencia colaborando con equipos de Data Engineering o desarrollo.\n🌍\n¿Qué te ofrecemos?\n💻\nTeletrabajo 100% real\ncon autonomía y flexibilidad.\n🏙️ Participación en un proyecto tecnológico estratégico para una gran entidad pública de Barcelona.\n🚀 Trabajo con tecnologías punteras en Big Data e Inteligencia Artificial.\n📈 Desarrollo profesional y crecimiento dentro de proyectos de alto impacto.\nInclusión en el programa de\nbeneficios y descuentos,\npara disfrutar de tus eventos, vacaciones, compras diarias y caprichos, beneficiándote de todos los descuentos que aporta el Quental Club Benefits! 🧾🎁\n📚Desarrollo de carrera en un ambiente colaborativo y con bonificaciones a tu\nformación continua\n, para que siempre estés actualizado y a la última en cuanto a tecnología y tendencias en transformación digital.\n🤝 Entorno colaborativo, innovador y orientado a la mejora continua.\n🌟 ¿Por qué este proyecto?\nPorque formarás parte de una transformación tecnológica que impulsa la evolución digital de servicios públicos y el uso inteligente de los datos para mejorar la sociedad.\nSi te motiva trabajar con datos, innovación y proyectos con impacto real…\n👉\nQueremos conocerte\n📊✨',
  'job_url': 'https://es.linkedin.com/jobs/view/%F0%9F%9A%80%F0%9F%93%8A-cient%C3%ADfico-a-de-datos-data-scientist-cient%C3%ADfic-de-dades-at-quental-4370562328?position=1&pageNum=0&refId=rNNze5b7SqZeHIQh9ZVUcw%3D%3D&trackingId=GjRKlYIVZwfvsrmEOYFJ8w%3D%3D',
  'job_description': '¿Te gustaría participar en un gran proyecto de modernización tecnológica que impacta directamente en la mejora de servicios públicos? 🌍\nBuscamos un/a\nCientífico/a de Datos\nque quiera formar parte de una iniciativa de actualización tecnológica de infraestructuras de aplicaciones, dentro de un entorno de IA, Big Data y mejora tecnológica avanzada.\nEl puesto es\nremoto 100%\n, aunque se valorará disponibilidad para asistir a reuniones muy esporádicas en Barcelona 🏙️.\n🎯 Serás una pieza clave en la definición, desarrollo y optimización de modelos analíticos y de inteligencia artificial, transformando datos en conocimiento estratégico que impulse la toma de decisiones y la mejora de servicios públicos.\n⚙️✨\n¿Qué harás en tu día a día?\n🧠 Definir objetivos analíticos y casos de uso de Inteligencia Artificial junto a negocio y equipos técnicos.\n📊 Realizar análisis exploratorio de datos para identificar patrones, tendencias y oportunidades de mejora.\n🤖 Diseñar, desarrollar, entrenar y optimizar modelos de Machine Learning y técnicas de analítica avanzada.\n📈 Evaluar rendimiento, validación y robustez de modelos mediante métricas y técnicas estadísticas.\n🧩 Seleccionar variables, preparar datasets y aplicar técnicas de feature engineering.\n🔬 Experimentar con algoritmos y metodologías para mejorar precisión y eficiencia de modelos.\n📉 Analizar resultados y generar insights accionables para negocio y stakeholders.\n🔗 Colaborar con equipos de Data Engineering para la integración y explotación de modelos en producción.\n☁️ Participar en entornos Big Data y ecosistemas cloud orientados a IA y analítica avanzada.\n📄 Documentar modelos, procesos analíticos y buenas prácticas metodológicas.\n🤝 Trabajar con equipos multidisciplinares (Arquitectura, Desarrollo, Negocio y Analítica).\n🧠\n¿Qué puedes aportarnos?\n📚 Titulación\nGrado en Estadística, Matemáticas, Física, Ingeniería Informática/Datos o similar\nMáster en Data Science, IA o equivalente.\n💼\nExperiencia\n⏳ Entre 2 y 8 años de experiencia en Ciencia de Datos, Analítica Avanzada o posiciones similares.\nExperiencia en desarrollo y evaluación de modelos de IA o Machine Learning en entornos reales.\n🛠️\nConocimientos técnicos\n🐍 Programación en Python aplicada a análisis de datos y modelos de IA.\n📊 Dominio de librerías de análisis y modelado (Pandas, NumPy, Scikit-learn, TensorFlow, PyTorch o similares).\n📈 Conocimientos sólidos en estadística, modelado predictivo y técnicas de Machine Learning.\n🧹 Experiencia en análisis exploratorio de datos y preparación de datasets.\n🗄️ Conocimientos de SQL y explotación de grandes volúmenes de datos.\n☁️ Conocimiento de ecosistemas Big Data y arquitecturas modernas de datos.\n📊 Experiencia en evaluación, validación y optimización de modelos analíticos.\n⭐\nMuy valorable\n🗣️ Nivel de comprensión y redacción en Catalán.\n⚡ Experiencia en procesamiento distribuido (PySpark o frameworks similares).\n🏛️ Experiencia en proyectos del sector público o grandes infraestructuras tecnológicas.\n☁️ Experiencia en entornos cloud aplicados a analítica avanzada e IA.\n📊 Experiencia en visualización de datos y comunicación de resultados analíticos.\n🤝 Experiencia colaborando con equipos de Data Engineering o desarrollo.\n🌍\n¿Qué te ofrecemos?\n💻\nTeletrabajo 100% real\ncon autonomía y flexibilidad.\n🏙️ Participación en un proyecto tecnológico estratégico para una gran entidad pública de Barcelona.\n🚀 Trabajo con tecnologías punteras en Big Data e Inteligencia Artificial.\n📈 Desarrollo profesional y crecimiento dentro de proyectos de alto impacto.\nInclusión en el programa de\nbeneficios y descuentos,\npara disfrutar de tus eventos, vacaciones, compras diarias y caprichos, beneficiándote de todos los descuentos que aporta el Quental Club Benefits! 🧾🎁\n📚Desarrollo de carrera en un ambiente colaborativo y con bonificaciones a tu\nformación continua\n, para que siempre estés actualizado y a la última en cuanto a tecnología y tendencias en transformación digital.\n🤝 Entorno colaborativo, innovador y orientado a la mejora continua.\n🌟 ¿Por qué este proyecto?\nPorque formarás parte de una transformación tecnológica que impulsa la evolución digital de servicios públicos y el uso inteligente de los datos para mejorar la sociedad.\nSi te motiva trabajar con datos, innovación y proyectos con impacto real…\n👉\nQueremos conocerte\n📊✨\nShow more\nShow less'},
 {'country': 'spain',
  'job_title': 'Data Scientist',
  'company_name': 'Sabadell Consumer Finance',
  'company_url': 'https://es.linkedin.com/company/sabadellconsumerfinance?trk=public_jobs_jserp-result_job-search-card-subtitle',
  'location': 'Sant Cugat del Vallès, Catalonia, Spain',
  'benefit': '',
  'posted': '1 day ago',
  'company_description': '¿Qué estamos buscando?\nActualmente nos encontramos en búsqueda de nuestro/nuestra futuro/futura Data Scientist cuya misión es participar en proyectos de analítica de datos mediante el desarrollo de procesos de reporting, data mining, generación de nuevas variables / indicadores así como modelos de analítica avanzada / cognitivos que ayuden en las acciones de cálculo de procesos corporativos / departamentales y reporting de las unidades del banco incrementando su eficiencia, eficacia y generando impacto en los márgenes de rentabilidad aportados por el cliente.\nHablemos del Proyecto...\nComo Data Scientist tu misión será:\nDesarrollar modelos enfocados a potenciar la gestión de anticipada mediante metodologías analíticas y de Machine Learning.\nRealizar las ETLs necesarias para la elaboración de los modelos analíticos.\nParticipar en la ejecución, control y mejora de los modelos y procesos que se encuentren actualmente calendarizados / programados.\nRealización de los procesos para el análisis de los datos (metodologías analíticas tradicionales, analítica avanzada (machine learning, Deep learning), desarrollo de sistemas cognitivos)\nDesarrollo hipótesis que permitan diseñar y probar experimentos analíticos, con el objetivo de identificar áreas de oportunidad y medir el impacto potencial de nuevas iniciativas.\nSeguimiento y pilotaje de las mejoras o tests que se lleven a cabo sobre los modelos.\nExtracción de conclusiones accionables a partir del análisis de datos, con capacidad para traducirlas en implicaciones para el negocio.\nParticipación en diversos proyectos de la Dirección que afecten a los modelos para anticipar el comportamiento de los clientes.\n¿Qué valoramos de tu candidatura?\nPosees titulación con perfil STEM (Estadística, matemáticas, Ingenierías) o similares.\nSe valorará positivamente si tienes máster en Data Scientist / Big Data.\nTienes conocimientos de Machine Learning. Además, tienes conocimientos avanzados de SAS y/o tecnologías para manejo de datos como Python, R, etc.\nPosees conocimiento de riesgo de crédito.\nTienes experiencia de 2 a 4 años en una posición similar.\n¿Qué te ofrecemos?\nSerás parte de un equipo de profesionales de primer nivel, con una excelente reputación en el sector.\nPodrás disfrutar de una amplia oferta formativa.\nAprenderás de la mano de Managers de referencia de las distintas direcciones.\nAmpliarás tu red de contactos a través de la colaboración y espacios de networking.\nContarás con opciones de desarrollo de carrera y movilidad dentro del Grupo. Somos un grupo bancario que sienta sus bases en los principios de meritocracia y el desarrollo de sus colaboradores.\nContratación indefinida y remuneración competitiva.\nBanco Sabadell está comprometido en promover ambientes de trabajo en los que se trate con respeto y dignidad a las personas, procurando el desarrollo profesional de la plantilla y garantizando la igualdad de oportunidades en su selección, formación y promoción ofreciendo un entorno de trabajo libre de cualquier discriminación por motivo de género, edad, orientación sexual, religión, etnia o cualquier otra circunstancia personal o social.\nBanco Sabadell forma parte de la red de empresas con el distintivo de “Igualdad en la Empresa” otorgado por el Ministerio de Igualdad.',
  'job_url': 'https://es.linkedin.com/jobs/view/data-scientist-at-sabadell-consumer-finance-4374274153?position=2&pageNum=0&refId=rNNze5b7SqZeHIQh9ZVUcw%3D%3D&trackingId=zHtEUcC%2FvVbZZvqT6u5c3w%3D%3D',
  'job_description': '¿Qué estamos buscando?\nActualmente nos encontramos en búsqueda de nuestro/nuestra futuro/futura Data Scientist cuya misión es participar en proyectos de analítica de datos mediante el desarrollo de procesos de reporting, data mining, generación de nuevas variables / indicadores así como modelos de analítica avanzada / cognitivos que ayuden en las acciones de cálculo de procesos corporativos / departamentales y reporting de las unidades del banco incrementando su eficiencia, eficacia y generando impacto en los márgenes de rentabilidad aportados por el cliente.\nHablemos del Proyecto...\nComo Data Scientist tu misión será:\nDesarrollar modelos enfocados a potenciar la gestión de anticipada mediante metodologías analíticas y de Machine Learning.\nRealizar las ETLs necesarias para la elaboración de los modelos analíticos.\nParticipar en la ejecución, control y mejora de los modelos y procesos que se encuentren actualmente calendarizados / programados.\nRealización de los procesos para el análisis de los datos (metodologías analíticas tradicionales, analítica avanzada (machine learning, Deep learning), desarrollo de sistemas cognitivos)\nDesarrollo hipótesis que permitan diseñar y probar experimentos analíticos, con el objetivo de identificar áreas de oportunidad y medir el impacto potencial de nuevas iniciativas.\nSeguimiento y pilotaje de las mejoras o tests que se lleven a cabo sobre los modelos.\nExtracción de conclusiones accionables a partir del análisis de datos, con capacidad para traducirlas en implicaciones para el negocio.\nParticipación en diversos proyectos de la Dirección que afecten a los modelos para anticipar el comportamiento de los clientes.\n¿Qué valoramos de tu candidatura?\nPosees titulación con perfil STEM (Estadística, matemáticas, Ingenierías) o similares.\nSe valorará positivamente si tienes máster en Data Scientist / Big Data.\nTienes conocimientos de Machine Learning. Además, tienes conocimientos avanzados de SAS y/o tecnologías para manejo de datos como Python, R, etc.\nPosees conocimiento de riesgo de crédito.\nTienes experiencia de 2 a 4 años en una posición similar.\n¿Qué te ofrecemos?\nSerás parte de un equipo de profesionales de primer nivel, con una excelente reputación en el sector.\nPodrás disfrutar de una amplia oferta formativa.\nAprenderás de la mano de Managers de referencia de las distintas direcciones.\nAmpliarás tu red de contactos a través de la colaboración y espacios de networking.\nContarás con opciones de desarrollo de carrera y movilidad dentro del Grupo. Somos un grupo bancario que sienta sus bases en los principios de meritocracia y el desarrollo de sus colaboradores.\nContratación indefinida y remuneración competitiva.\nBanco Sabadell está comprometido en promover ambientes de trabajo en los que se trate con respeto y dignidad a las personas, procurando el desarrollo profesional de la plantilla y garantizando la igualdad de oportunidades en su selección, formación y promoción ofreciendo un entorno de trabajo libre de cualquier discriminación por motivo de género, edad, orientación sexual, religión, etnia o cualquier otra circunstancia personal o social.\nBanco Sabadell forma parte de la red de empresas con el distintivo de “Igualdad en la Empresa” otorgado por el Ministerio de Igualdad.\nShow more\nShow less'},
 {'country': 'spain',
  'job_title': 'Data Scientist',
  'company_name': 'Linde Material Handling Iberica, SA',
  'company_url': 'https://es.linkedin.com/company/linde-material-handling-iberica-sa?trk=public_jobs_jserp-result_job-search-card-subtitle',
  'location': 'Barcelona, Catalonia, Spain',
  'benefit': '',
  'posted': '2 weeks ago',

In [13]:
all_jobs[0]["job_url"]

'https://es.linkedin.com/jobs/view/junior-data-scientist-at-joinrs-4373566199?position=1&pageNum=0&refId=%2FKjwEcZtc02n2BegeUOtdg%3D%3D&trackingId=FUxAH%2B6v8LCz3%2FD7CeRO2w%3D%3D'

In [12]:
import pandas as pd

In [24]:
df = pd.DataFrame(all_jobs)
df.head()

,country,job_title,company_name,company_url,location,benefit,posted,company_description,job_url,job_description
0,spain,🚀📊 Científico/a de Datos (Data Scientist) (Cie...,Quental,https://es.linkedin.com/company/quental?trk=pu...,"Barcelona, Catalonia, Spain",,2 weeks ago,¿Te gustaría participar en un gran proyecto de...,https://es.linkedin.com/jobs/view/%F0%9F%9A%80...,¿Te gustaría participar en un gran proyecto de...
1,spain,Data Scientist,Sabadell Consumer Finance,https://es.linkedin.com/company/sabadellconsum...,"Sant Cugat del Vallès, Catalonia, Spain",,1 day ago,¿Qué estamos buscando?\nActualmente nos encont...,https://es.linkedin.com/jobs/view/data-scienti...,¿Qué estamos buscando?\nActualmente nos encont...
2,spain,Data Scientist,"Linde Material Handling Iberica, SA",https://es.linkedin.com/company/linde-material...,"Barcelona, Catalonia, Spain",,2 weeks ago,Linde Material Handling is among the world lea...,https://es.linkedin.com/jobs/view/data-scienti...,Linde Material Handling is among the world lea...
3,spain,Data Scientist - 100% Teletrabajo,Nunegal Consulting,https://es.linkedin.com/company/nunegal?trk=pu...,Spain,,1 week ago,¿Tienes experiencia como Data Scientist? ¿Te i...,https://es.linkedin.com/jobs/view/data-scienti...,¿Tienes experiencia como Data Scientist? ¿Te i...
4,spain,MACHINE LEARNING ENGINEER / DATA ENGINEER,TENDAM,https://es.linkedin.com/company/tendam?trk=pub...,Greater Madrid Metropolitan Area,,2 weeks ago,MACHINE LEARNING ENGINEER / DATA ENGINEER\nAt ...,https://es.linkedin.com/jobs/view/machine-lear...,MACHINE LEARNING ENGINEER / DATA ENGINEER\nAt ...

In [18]:
df.shape

(69, 10)

In [26]:
df.to_csv("analyst_jun.csv", index=False)

In [15]:
def filter_data_ai_jobs(df):
    return df[df["job_title"].str.contains("data|ai", case=False, na=False)]

In [16]:
df_filtered = filter_data_ai_jobs(df)

In [17]:
df_filtered.shape

(23, 10)

In [24]:
df_filtered.head()

,country,job_title,company_name,company_url,location,benefit,posted,company_description,job_url,job_description
0,spain,Data Scientist Intern - Data Platform & AI,Zurich Insurance,https://ch.linkedin.com/company/zurich-insuran...,"Barcelona, Catalonia, Spain",,,We Are Waiting for You\nHi there future intern...,https://es.linkedin.com/jobs/view/data-scienti...,We Are Waiting for You\nHi there future intern...
1,spain,Programa Talento Joven - Data Science,Evolve,https://es.linkedin.com/school/evolve-es/?trk=...,Spain,Be an early applicant,,Descripción de la oferta\nEn nuestro Programa ...,https://es.linkedin.com/jobs/view/programa-tal...,Descripción de la oferta\nEn nuestro Programa ...
2,spain,Data Engineer / Data Scientist,Inetum,https://fr.linkedin.com/company/inetum?trk=pub...,"Madrid, Community of Madrid, Spain",,,Descripción de la empresa\nInetum es líder eur...,https://es.linkedin.com/jobs/view/data-enginee...,Descripción de la empresa\nInetum es líder eur...
3,spain,Machine Learning Engineer - AI Data Trainer,Alignerr,https://www.linkedin.com/company/alignerr?trk=...,Spain,,,"Location: Remote\nAbout The Job\nAt Alignerr, ...",https://es.linkedin.com/jobs/view/machine-lear...,"Location: Remote\nAbout The Job\nAt Alignerr, ..."
4,spain,Junior Data Scientist – Proyectos reales y evo...,Evolve,https://es.linkedin.com/school/evolve-es/?trk=...,Spain,Be an early applicant,,Descripción de la oferta\nEn nuestro Programa ...,https://es.linkedin.com/jobs/view/junior-data-...,Descripción de la oferta\nEn nuestro Programa ...

In [21]:
df_filtered_junior = df_filtered[df_filtered["job_title"].str.contains("junior", case=False, na=False)]

In [22]:
df_filtered_junior.shape

(4, 10)